version: "2.3"
services:
  switch:
    restart: always
    image: "luscis/openlan:latest.x86_64"
    privileged: true
    network_mode: host
    entrypoint: ["/var/openlan/script/switch.sh", "start"]
    volumes:
      - /opt/openlan/etc/openlan:/etc/openlan
  proxy:
    restart: always
    image: "luscis/openlan:latest.x86_64"
    network_mode: host
    entrypoint: ["/usr/bin/openlan-proxy", "-conf", "/etc/openlan/proxy.json", "-log:file", "/dev/null"]
    volumes:
      - /opt/openlan/etc/openlan:/etc/openlan
    depends_on:
      - switch